---
title: "Projet Dettes par pays"
author: "Margaux Bailleul & Oriane Duclos"
date: "2023-11-22"
output: pdf_document
---

```{r}
data <- read.csv("archive/Dette_parpays.csv", header = TRUE)
head(data)
```

```{r}
summary(data)
```

Selection individu 

```{r}
# Assurez-vous que votre dataframe s'appelle 'df'
selected_countries <- c("South Korea", "Suriname", "Belgium", "Guinea", "Comoros", 
                        "Qatar", "New Zealand", "Paraguay", "Madagascar", "Gabon", 
                        "Austria", "Portugal", "Algeria", "Morocco", "France", 
                        "Libya", "Italy", "Singapore", "Lesotho", "Ghana", 
                        "United Kingdom", "Seychelles", "Honduras", "Netherlands", 
                        "Spain")

# Création d'un nouveau dataframe avec uniquement les pays sélectionnés
data <- data[data$Country.Name %in% selected_countries, ]

# Affichage des premières lignes du nouveau dataframe
head(data)

```


Transformation en numerique et suppression colonne inutile 

```{r}
# Suppression des colonnes 'Region' et 'Image.URL' sans utiliser dplyr
data <- data[, !(names(data) %in% c("region", "Image.URL"))]


for (colname in names(data)) {
  # Vérifie si le nom de la colonne commence par 'X' suivi de 4 chiffres
  if (grepl("^X[0-9]{4}$", colname)) {
    # Suppression des virgules et conversion en numérique
    data[[colname]] <- as.numeric(gsub(",", ".", data[[colname]]))

    # Renommage de la colonne pour enlever le 'X'
    names(data)[names(data) == colname] <- substr(colname, 2, nchar(colname))
  }
}

head(data)


```



```{r}

library(tidyr)


long_data <- pivot_longer(data, cols = -Country.Name, names_to = "Année", values_to = "Dette")


head(long_data)

df <- pivot_wider(long_data, names_from = Country.Name, values_from = Dette)

head(df)

```


# Selection des pays ayant une valeur de dette de 1990 à 2021 

```{r}
library(ggplot2)
ggplot(data = df) + aes(x = df$Année, y = df$Portugal) + 
  geom_point()
```

```{r}
library(ggplot2)
library(tidyr)

# Exemple de réorganisation des données avec gather
df_long <- gather(df, key = "Pays", value = "Valeur", -Année)
df_long <- df_long[order(df_long$Année), ]

# Tracer le graphique avec ggplot
ggplot(data = df_long, aes(x = Année, y = Valeur, color = Pays)) +
  geom_point() +
  labs(title = "Données par pays")
```
```{r}
ggplot(data = df_long, aes(x = Année, y = Valeur, color = Pays)) +
  geom_point() +
  labs(title = "Données par pays")
```






